language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  matrix:
    - TOXENV="py33"
    - TOXENV="py34"
    - TOXENV="py35"
    - TOXENV="py36"
    - TOXENV="pypy"
install:
  - pip install tox
script:
  - tox -e $TOXENV
